### ISSUE TITLE
Quality code checklist

### ISSUE THREAD

**Issue by Luni-4** [sifis-home/policy-translation-point#1]
WP2 requires a code that is fully tested and easily reproducible, so the following checks MUST be implemented in this project in order to be compliant with the SIFIS-Home specifications.

- [x] Does the project have a `README.md` that explains how this software works ?
- [x] Does the project have a `LICENSE` file? 
    - If possible use either [MIT](https://spdx.org/licenses/MIT) or other compatible licenses. 
- [x] Does the project have a [GitHub Action](https://github.com/features/actions) (you may use [sifis-generate](https://crates.io/crates/sifis-generate) to create it)?
   - **Copy this [CI](https://github.com/sifis-home/ace-entities/blob/master/.github/workflows/github.yml) script adapting it to your needs**
   - [x] Does it upload the code coverage somewhere? 
   -  These [lines](https://github.com/sifis-home/ace-entities/blob/master/.github/workflows/github.yml#L44-L68) compute code coverage, create the relative badge, and push everything on `gh-pages` branch. 
   - Then the following line `
  [![coverage](https://raw.githubusercontent.com/sifis-home/policy-translation-point/gh-pages/reports/jacoco.svg 'Code Coverage')](https://sifis-home.github.io/policy-translation-point/reports/index.html)
` is added to visualize the badge in README
   - [x] Does it manage the release of the code? (Continuous Delivery) 
   - **Have a look at this [CI](https://github.com/sifis-home/ace-entities/blob/master/.github/workflows/deploy.yml) script**
- [x] Does it have a DockerFile?
- [x]  Is the Dockerfile published on `ghcr`, the Github hub for Docker images? 
    - **Contained in this [CI](https://github.com/sifis-home/ace-entities/blob/master/.github/workflows/github.yml) script**
